<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Yoon Hong Park" />

<meta name="date" content="2018-11-13" />

<title>34600 Problem Set 3</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});
</script>

<!-- code folding -->






<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Yoon's Archive</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About me</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Program Evaluation (R/Stata)
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="PE_pset3.html">Ban the Box (DID)</a>
    </li>
    <li>
      <a href="PS2-f2018.html">Very Low Birth Weight (RDD)</a>
    </li>
    <li>
      <a href="pePS1.html">Mexican Universal Health Insurance (ITT/LATE)</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    GIS and Spatial Analysis (R)
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="mapping3-ChiTrauma.html">Chicago Trauma Center Service Area</a>
    </li>
    <li>
      <a href="mapping2-ILInc.html">Illinois Income Distribution</a>
    </li>
    <li>
      <a href="mapping1-ChiHIV.html">Chicago HIV Prevalence</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Policy Analysis (R)
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Rps4.html">Health Care Data</a>
    </li>
    <li>
      <a href="Rps3.html">Flight Data 2</a>
    </li>
    <li>
      <a href="Rps2.html">Flight Data 1</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Programming (Python)
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Scraping</li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="section-header">



<h1 class="title toc-ignore">34600 Problem Set 3</h1>
<h4 class="author"><em>Yoon Hong Park</em></h4>
<h4 class="date"><em>11/13/2018</em></h4>

</div>


<p><br></p>
<p>For this assignment, provide a write-up where you answer the questions below, selectively cutting and pasting output where needed. Be concise in your write-up; excess wordiness will be penalized. Also, submit a log file that includes commands and results for your entire analysis. The assignment makes use of AganStarrQJEData.dta, which you can find on Canvas.</p>
<p>In this problem set we will reproduce some of Amanda Agan and Sonja Starr’s basic results, so start by reading their paper (Ban the box, criminal records, and racial discrimination: A field experiment), which you can find on Canvas.</p>
<p><br style="line-height:1"></br></p>
<div id="section-questions" class="section level2">
<h2><strong>Questions</strong></h2>
<div id="section-set-up" class="section level3">
<h3><strong>Set-up</strong></h3>
<pre class="r"><code># Load libraries
library(tidyverse)
library(broom)
library(foreign)
library(readstata13)
library(haven)
library(labelled)
library(statar)
library(rdd)
library(stargazer)
library(&quot;plm&quot;)
library(lmtest)
library(multiwayvcov)</code></pre>
<pre class="r"><code># Call the data
data &lt;- read_dta(&quot;AganStarrQJEData.dta&quot;)

attr(data$crime, &quot;label&quot;)
head(data)

data &lt;- filter(data, remover != -1)</code></pre>
<p><br><br></p>
</div>
<div id="section-q1" class="section level3">
<h3><strong>Q1</strong></h3>
<p>For this question, restrict your analysis to the set of job applications that asked about criminal records (“Box” applications) in the before period (“pre-BTB” period). (Note: there are some applications that did not have a box in the pre-BTB period, but then added them in the post-period. Agan and Star code these as “remover = -1” in their data and call them “reverse compliers.” Exclude these observations from your analysis throughout this assignment.)</p>
<p><br></p>
<div id="section-a" class="section level4">
<h4><strong>a)</strong></h4>
<p>What is the average callback rate for people who committed crimes? For those who didn’t? Is the difference statistically significant?</p>
<p><br></p>
<p><strong>Answer</strong> <br> The average callback rate for people who committed crimes is about <u>8.46%</u> while that for people who did not commit crimes is about <u>13.57%</u>. The two sample t-test with the very small p-value = 0.000025 suggest that this difference of <u>5.2%</u> is statistically significant.</p>
<pre class="r"><code>c_crime &lt;-
  data %&gt;%
  filter(crimbox == 1, pre == 1, crime == 1)

n_crime &lt;-
  data %&gt;%
  filter(crimbox == 1, pre == 1, crime == 0)

t.test(n_crime$response, c_crime$response, var.equal = TRUE)</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  n_crime$response and c_crime$response
## t = 4.2226, df = 2653, p-value = 2.496e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.02738584 0.07487022
## sample estimates:
##  mean of x  mean of y 
## 0.13570887 0.08458084</code></pre>
<p><br></p>
</div>
<div id="section-b" class="section level4">
<h4><strong>b)</strong></h4>
<p>Can we interpret this as a causal effect? Explain briefly.</p>
<p><br></p>
<p><strong>Answer</strong> <br> As this study is based on the randomized-control-test (RCT) that randomized the assignment of treatment (conviction status), the difference that we simply calculated above can be inferred as the causal effect of previous conviction status.</p>
<p><br><br></p>
</div>
</div>
<div id="section-q2" class="section level3">
<h3><strong>Q2</strong></h3>
<p>Now consider just the “Box” applications but include both the pre- and post-BTB periods.</p>
<p><br></p>
<div id="section-a-1" class="section level4">
<h4><strong>a)</strong></h4>
<p>Regress callback rates on race, GED, and employment gap. Include “chain” and “center” fixed effects. Does race appear to have an effect on callback rates? Does this coefficient have a causal interpretation?</p>
<p><br></p>
<p><strong>Answer</strong> <br> The race seems to have a statistically significant effect on the callback rate, implying that white people are 2.43% more likely to get a positive response than the non-white. However, to conclude that this coefficient implies the causality, we need to test other models by adding more variables so that we can avoid the omitted-variable bias.</p>
<pre class="r"><code>compliers &lt;- filter(data, remover == 1)

callback_wo_convic &lt;-
  lm(response ~ white + ged + empgap + factor(cogroup_comb) + factor(center),
     data = compliers)

# Cluster standard errors
callback_wo_convic$clse &lt;- cluster.vcov(callback_wo_convic, compliers$chain_id)
callback_wo_convic_test &lt;- coeftest(callback_wo_convic, callback_wo_convic$clse)


# Show Results from Regression
stargazer(
  callback_wo_convic,
  type = &quot;text&quot;,
  style = &quot;aer&quot;,
  digits = 5,
  title = &quot;Effects of Applicant Characteristics on Callback Rates&quot;,
  dep.var.labels = &quot;Callback to Box Applicants&quot;,
  covariate.labels = c(&quot;White&quot;, 
                       &quot;GED&quot;,
                       &quot;Employment Gap&quot;),
  omit = c(&quot;cogroup_comb&quot;, &quot;center&quot;),
  omit.labels = c(&quot;Chain FE&quot;, &quot;Center FE&quot;),
  se = list(callback_wo_convic_test[, 2])
)</code></pre>
<pre><code>## 
## Effects of Applicant Characteristics on Callback Rates
## ==========================================================
##                           Callback to Box Applicants      
## ----------------------------------------------------------
## White                             0.02432***              
##                                   (0.00783)               
##                                                           
## GED                                0.00632                
##                                   (0.00759)               
##                                                           
## Employment Gap                     0.00629                
##                                   (0.00708)               
##                                                           
## Constant                           0.01797                
##                                   (0.04682)               
##                                                           
## Chain FE                             Yes                  
## Center FE                            Yes                  
## Observations                        4,794                 
## R2                                 0.12349                
## Adjusted R2                        0.09867                
## Residual Std. Error          0.30825 (df = 4661)          
## F Statistic              4.97502*** (df = 132; 4661)      
## ----------------------------------------------------------
## Notes:              ***Significant at the 1 percent level.
##                     **Significant at the 5 percent level. 
##                     *Significant at the 10 percent level.</code></pre>
<p><br></p>
</div>
<div id="section-b-1" class="section level4">
<h4><strong>b)</strong></h4>
<p>Estimate the model again, but without the chain and center fixed effects. Does the coefficient on “white” change? Why is it important to include chain and center fixed effects?</p>
<p><br></p>
<p><strong>Answer</strong> <br> There was not much change in the “coefficient” itself. The standard error is larger in the model without fixed effects than in the model with them. This implies that the chain and center fixed effects make the model more precise by capturing unobserved heterogeneity that is fixed at geographic-center level and chain-level.</p>
<pre class="r"><code>callback_wo_fe &lt;- lm(response ~ white + ged + empgap, data = compliers)

# Cluster standard errors
callback_wo_fe$clse &lt;- cluster.vcov(callback_wo_fe, compliers$chain_id)
callback_wo_fe_test &lt;- coeftest(callback_wo_fe, callback_wo_fe$clse)

# Show Results from Regression 
stargazer(
  callback_wo_fe,
  type = &quot;text&quot;,
  style = &quot;aer&quot;,
  digits = 4,
  title = &quot;Effects of Applicant Characteristics on Callback Rates&quot;,
  dep.var.labels = &quot;Callback to Box Applicants&quot;,
  covariate.labels = c(&quot;White&quot;, 
                       &quot;GED&quot;,
                       &quot;Employment Gap&quot;),
  omit = c(&quot;cogroup_comb&quot;, &quot;center&quot;),
  omit.labels = c(&quot;Chain FE&quot;, &quot;Center FE&quot;), 
  se = list(callback_wo_fe_test[, 2])
)</code></pre>
<pre><code>## 
## Effects of Applicant Characteristics on Callback Rates
## ==========================================================
##                           Callback to Box Applicants      
## ----------------------------------------------------------
## White                             0.0242***               
##                                    (0.0079)               
##                                                           
## GED                                 0.0082                
##                                    (0.0088)               
##                                                           
## Employment Gap                      0.0059                
##                                    (0.0079)               
##                                                           
## Constant                          0.1006***               
##                                    (0.0160)               
##                                                           
## Chain FE                              No                  
## Center FE                             No                  
## Observations                        4,794                 
## R2                                  0.0016                
## Adjusted R2                         0.0010                
## Residual Std. Error           0.3245 (df = 4790)          
## F Statistic                 2.5790* (df = 3; 4790)        
## ----------------------------------------------------------
## Notes:              ***Significant at the 1 percent level.
##                     **Significant at the 5 percent level. 
##                     *Significant at the 10 percent level.</code></pre>
<p><br></p>
</div>
<div id="section-c" class="section level4">
<h4><strong>c)</strong></h4>
<p>Now add the “conviction” variable. What happens to the coefficient on “white”? If the coefficient changes, does this mean that the previous regression was subject to omitted variable bias?</p>
<p><br></p>
<p><strong>Answer</strong> <br> It was reasonable to suspect that the previous model might omit some other variables that could potentially be correlated with the race and also affect the callback rate, which can be the “conviction” variable. The coefficient on “white” does not change much although it indeed changes. Since the correlation between the “conviction” variable and the “race” variable is low (0.01913946), the small change in the coefficient does not suggest that the previous regression model was subject to omitted variable bias.</p>
<pre class="r"><code># Add &quot;Conviction&quot; to b)
callback_w_convic &lt;- lm(response ~ crime + white + ged + empgap, data = compliers)

# Cluster standard errors
callback_w_convic$clse &lt;- cluster.vcov(callback_w_convic, compliers$chain_id)
callback_w_convic_test &lt;- coeftest(callback_w_convic, callback_w_convic$clse)

# Show Results from Regression
stargazer(
  callback_w_convic,
  type = &quot;text&quot;,
  out = &quot;.txt&quot;,
  style = &quot;aer&quot;,
  digits = 4,
  title = &quot;Effects of Applicant Characteristics on Callback Rates&quot;,
  dep.var.labels = &quot;Callback to Box Applicants&quot;,
  covariate.labels = c(&quot;Conviction&quot;,
                       &quot;White&quot;, 
                       &quot;GED&quot;,
                       &quot;Employment Gap&quot;),
  omit = c(&quot;cogroup_comb&quot;, &quot;center&quot;),
  omit.labels = c(&quot;Chain FE&quot;, &quot;Center FE&quot;),
  se = list(callback_w_convic_test[, 2])
)</code></pre>
<pre><code>## 
## Effects of Applicant Characteristics on Callback Rates
## ==========================================================
##                           Callback to Box Applicants      
## ----------------------------------------------------------
## Conviction                        -0.0370***              
##                                    (0.0078)               
##                                                           
## White                             0.0249***               
##                                    (0.0086)               
##                                                           
## GED                                 0.0070                
##                                    (0.0087)               
##                                                           
## Employment Gap                      0.0058                
##                                    (0.0078)               
##                                                           
## Constant                          0.1196***               
##                                    (0.0171)               
##                                                           
## Chain FE                              No                  
## Center FE                             No                  
## Observations                        4,794                 
## R2                                  0.0049                
## Adjusted R2                         0.0040                
## Residual Std. Error           0.3240 (df = 4789)          
## F Statistic                5.8463*** (df = 4; 4789)       
## ----------------------------------------------------------
## Notes:              ***Significant at the 1 percent level.
##                     **Significant at the 5 percent level. 
##                     *Significant at the 10 percent level.</code></pre>
<pre class="r"><code># Add &quot;Conviction&quot; to a)
callback_w_convic_fe &lt;- lm(response ~ crime + white + ged + empgap + factor(cogroup_comb) + factor(center), data = compliers)

# Cluster standard errors
callback_w_convic_fe$clse &lt;- cluster.vcov(callback_w_convic_fe, compliers$chain_id)
callback_w_convic_fe_test &lt;- coeftest(callback_w_convic_fe, callback_w_convic_fe$clse)

# Show Results from Regression
stargazer(
  callback_w_convic_fe,
  type = &quot;text&quot;,
  out = &quot;.txt&quot;,
  style = &quot;aer&quot;,
  digits = 4,
  title = &quot;Effects of Applicant Characteristics on Callback Rates&quot;,
  dep.var.labels = &quot;Callback to Box Applicants&quot;,
  covariate.labels = c(&quot;Conviction&quot;,
                       &quot;White&quot;,
                       &quot;GED&quot;,
                       &quot;Employment Gap&quot;
                       ),
  omit = c(&quot;cogroup_comb&quot;, &quot;center&quot;),
  omit.labels = c(&quot;Chain FE&quot;, &quot;Center FE&quot;),
  se = list(callback_w_convic_fe_test[, 2])
)</code></pre>
<pre><code>## 
## Effects of Applicant Characteristics on Callback Rates
## ==========================================================
##                           Callback to Box Applicants      
## ----------------------------------------------------------
## Conviction                        -0.0323***              
##                                    (0.0079)               
##                                                           
## White                             0.0249***               
##                                    (0.0084)               
##                                                           
## GED                                 0.0052                
##                                    (0.0076)               
##                                                           
## Employment Gap                      0.0062                
##                                    (0.0070)               
##                                                           
## Constant                            0.0364                
##                                    (0.0474)               
##                                                           
## Chain FE                             Yes                  
## Center FE                            Yes                  
## Observations                        4,794                 
## R2                                  0.1259                
## Adjusted R2                         0.1010                
## Residual Std. Error           0.3079 (df = 4660)          
## F Statistic               5.0476*** (df = 133; 4660)      
## ----------------------------------------------------------
## Notes:              ***Significant at the 1 percent level.
##                     **Significant at the 5 percent level. 
##                     *Significant at the 10 percent level.</code></pre>
<pre class="r"><code>cor(compliers$white, compliers$crime)</code></pre>
<pre><code>## [1] 0.01913946</code></pre>
<p><br><br></p>
</div>
</div>
<div id="section-q3" class="section level3">
<h3><strong>Q3</strong></h3>
<p>The authors estimate the following model for different subsets of the data, where “Box” is an indicator for whether the application had a box asking about employment, and X is a vector of covariates:</p>
<p><span class="math display">\[Callback_{ij} = \alpha + \beta_{1}Box_{j} + \beta_{2}White_{i} + \beta_{3}Box_{j}*White_{i} + X_{i}\gamma + \varepsilon_{ij}\]</span> <br></p>
<div id="section-a-2" class="section level4">
<h4><strong>a)</strong></h4>
<p>Suppose they run this regression on the full sample, which includes both Box and non-Box applications, but only in the pre-period (don’t actually do this yet). What do <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta_1\)</span>, <span class="math inline">\(\beta_2\)</span>, and <span class="math inline">\(\beta_3\)</span> tell you?</p>
<p><br></p>
<p><strong>Answer</strong> <br> <span class="math inline">\(\alpha\)</span> indicates the callback rate (averaged) for non-white applicants to non-Box employers in the pre-Ban-the-Box period, controlled for other covariates. <span class="math inline">\(\beta_1\)</span> indicates the average difference in the callback rate between the non-white applicants to Box stores and those to non-Box stores. <span class="math inline">\(\beta_2\)</span> indicates the average difference in the callback rate between the White applicants and the Black applicants to non-Box employers.</p>
<p><span class="math inline">\(\beta_2 + \beta_3\)</span> indicates the difference in the callback rates between the White applicants and the Black applicants when the employers had the Ban, and that <span class="math inline">\(\beta_1 + \beta_3\)</span> indicates the difference in the callback rates between the White applicants to Box stores and the White applicants to non-Box stores. Therefore, <span class="math inline">\(\beta_3\)</span> indicates the average gap between the difference in the callback rates between the white applicants to non-box employers and those to box employers and the difference in the callback rates between the non-white applicants to non-box employers and those to box employers.</p>
<p><br></p>
</div>
<div id="section-b-2" class="section level4">
<h4><strong>b)</strong></h4>
<p>Do you think “Box” and “non-Box” stores might differ in systematic ways, besides their decision to include a box asking about criminal history? In other words, do we think this variable is “as-if” randomly assigned?</p>
<p><br></p>
<p><strong>Answer</strong> <br> It is reasonable to suspect that those stores might be systematically different due to the characteristics of their geographic locations and the types of stores. Indeed the authors compare some characteristics of the Box stores with those of non-Box stores in <a href="https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/qje/133/1/10.1093_qje_qjx028/2/qjx028_supp.pdf?Expires=1554270516&amp;Signature=aAnUYOm2aXNFdd5Ipto~fmxgB~f-k57MCrpggnEAND6JVAP3isuTiLqVkBiXoDmzj4-HjoRuSmSxlPPXTQ1ZKvMwAVniGCD8FeR33tvWk8hT6zxgcT~n86w9XKWs74F3qhSUktr9pwbCBoEU~dklOWjFfdQTuaNvZCVsUMhXjs3jxVoRo~bHVDF8k00Lxu8-MBgXm8Txc9w0uonIA57QVzELDIEQSNhoVKnVfrdD8gO2xQiwfMC-tqk~c6E2UYCF3T1pWF0wFT~OgNcaBXOdj0kje0R~VXiQxH3C5e7Im6IDWiFfSDx0d2VYgaPS1fFfsCIPtfj1nsj6v7ToGxk~Pg__&amp;Key-Pair-Id=APKAIE5G5CRDK6RD3PGA">Online Appendix A3</a>. The authors found only one systematic difference, which means the retail stores are more likely to have Box than non-retail stores, but they argued that their additional analyses having the “retail” variable in the regression model were not different from the model with the “retail” variable except for the interaction term, <span class="math inline">\(Box_j \times White_i\)</span>. Therefore, we do not need to think the “retail” variable “as-if” randomly assigned.</p>
<p><br></p>
</div>
<div id="section-c-1" class="section level4">
<h4><strong>c)</strong></h4>
<p>Suppose they run the regression on just the “Box” applications in both periods (again, don’t do this yet). What is the interpretation of the coefficients now? (remover == 1)</p>
<p><br></p>
<p><strong>Answer</strong> <br> If we limit the data to Ban-the-Box compliers, in the regression on both periods, the variation in the “Box” variable is solely explained by being in pre-BTB period. In other words, in this regression, the Box variable indicates whether an observation is in the pre-BTB period.</p>
<p>Then, <span class="math inline">\(\alpha\)</span> indicates the callback rate (averaged) for non-white applicants in the post-BTB period, controlled for other covariates, or simply “intercepts for non-white applicants in the post-BTB period.” <span class="math inline">\(\beta_1\)</span> indicates the average difference in the callback rate between non-white applicants in the pre-BTB period and those in the post-BTB period. <span class="math inline">\(\beta_2\)</span> indicates the average difference in the callback rate between white applicants and non-white applicants in the post-BTB period. <span class="math inline">\(\beta_3\)</span> indicates the average gap between the difference in the callback rates between the white applicants in the pre-BTB period and those in the post-BTB period and the difference in the callback rates between the non-white applicants in the pre-BTB period and those in the post-BTB period.</p>
<pre class="r"><code>compliers %&gt;% filter(crimbox != pre)</code></pre>
<pre><code>## # A tibble: 0 x 62
## # ... with 62 variables: nj &lt;dbl&gt;, nyc &lt;dbl&gt;, app_date_d &lt;date&gt;,
## #   pre &lt;dbl&gt;, post &lt;dbl+lbl&gt;, storeid &lt;dbl&gt;, chain_id &lt;dbl&gt;,
## #   center &lt;dbl&gt;, crimbox &lt;dbl+lbl&gt;, crime &lt;dbl+lbl&gt;, drugcrime &lt;dbl&gt;,
## #   propertycrime &lt;dbl&gt;, ged &lt;dbl&gt;, empgap &lt;dbl&gt;, white &lt;dbl+lbl&gt;,
## #   black &lt;dbl&gt;, remover &lt;dbl+lbl&gt;, noncomplier_store &lt;dbl&gt;,
## #   balanced &lt;dbl&gt;, response &lt;dbl&gt;, response_date_d &lt;dbl&gt;,
## #   daystoresponse &lt;dbl&gt;, interview &lt;dbl&gt;, cogroup_comb &lt;dbl&gt;,
## #   cogroup_njnyc &lt;dbl&gt;, post_cogroup_njnyc &lt;dbl&gt;,
## #   white_cogroup_njnyc &lt;dbl&gt;, ged_cogroup_njnyc &lt;dbl&gt;,
## #   empgap_cogroup_njnyc &lt;dbl&gt;, box_white &lt;dbl&gt;, pre_white &lt;dbl&gt;,
## #   post_white &lt;dbl&gt;, white_nj &lt;dbl&gt;, post_remover_ged &lt;dbl&gt;,
## #   post_ged &lt;dbl&gt;, remover_ged &lt;dbl&gt;, post_remover_empgap &lt;dbl&gt;,
## #   post_empgap &lt;dbl&gt;, remover_empgap &lt;dbl&gt;, post_remover_white &lt;dbl&gt;,
## #   post_remover &lt;dbl&gt;, remover_white &lt;dbl&gt;, raerror &lt;dbl&gt;, retail &lt;dbl&gt;,
## #   num_stores &lt;dbl&gt;, avg_salesvolume &lt;dbl&gt;, avg_num_employees &lt;dbl&gt;,
## #   retail_white &lt;dbl&gt;, retail_post &lt;dbl&gt;, retail_post_white &lt;dbl&gt;,
## #   percblack &lt;dbl&gt;, percwhite &lt;dbl&gt;, tot_crime_rate &lt;dbl&gt;,
## #   nocrimbox &lt;dbl+lbl&gt;, nocrime_box &lt;dbl+lbl&gt;, nocrime_pre &lt;dbl+lbl&gt;,
## #   response_white &lt;dbl&gt;, response_black &lt;dbl&gt;, response_ged &lt;dbl&gt;,
## #   response_hsd &lt;dbl&gt;, response_empgap &lt;dbl&gt;, response_noempgap &lt;dbl&gt;</code></pre>
<p><br><br></p>
</div>
</div>
<div id="section-q4" class="section level3">
<h3><strong>Q4</strong></h3>
<p>For the below estimations, include controls for employment gap and ged, as well as center fixed effects. Again, exclude the so-called “reverse compliers.”</p>
<div id="section-a-3" class="section level4">
<h4><strong>a)</strong></h4>
<p>Estimate the model from question 3 on both “Box” and non-“Box” applications in just the pre-period.</p>
<p><br></p>
<p><strong>Answer</strong> <br> The callback rate (averaged) for black applicants to non-Box stores in the pre-BTB period, controlled for other covariates, or simply <span class="math inline">\(\alpha\)</span>, is 0.0847. <span class="math inline">\(\beta_1\)</span>, the average difference in the callback rate between the non-white applicants to Box stores and those to non-Box stores, is 0.0150. <span class="math inline">\(\beta_2\)</span>, the average difference in the callback rate between the white applicants and the non-white applicants to non-Box stores, is 0.0315. <span class="math inline">\(\beta_3\)</span> is -0.0302. Except for <span class="math inline">\(\beta_1\)</span>, other coefficients are found to be statistically significant.</p>
<pre class="r"><code>pre_btb &lt;- data %&gt;% filter(post == 0)
box_non_box_callback &lt;- lm(response ~ box_white + white + crimbox + ged + empgap + factor(center), data = pre_btb)

# Cluster standard errors
box_non_box_callback$clse &lt;- cluster.vcov(box_non_box_callback, pre_btb$chain_id)
box_non_box_callback_test &lt;- coeftest(box_non_box_callback, box_non_box_callback$clse)

# Show Results from Regression
stargazer(
  box_non_box_callback,
  type = &quot;text&quot;,
  out = &quot;.txt&quot;,
  style = &quot;aer&quot;,
  digits = 4,
  title = &quot;Effects of Applicant Characteristics on Callback Rates&quot;,
  dep.var.labels = &quot;Callback to Box / non-Box Applicants&quot;,
  covariate.labels = c(&quot;Box * White&quot;, 
                       &quot;White&quot;,
                       &quot;Box&quot;),
  omit = c(&quot;ged&quot;, &quot;empgap&quot;, &quot;center&quot;),
  omit.labels = c(&quot;Controls - GED&quot;, &quot;Controls - Employment Gap&quot;, &quot;Center FE&quot;),
  se = list(box_non_box_callback_test[, 2])
)</code></pre>
<pre><code>## 
## Effects of Applicant Characteristics on Callback Rates
## ================================================================
##                            Callback to Box / non-Box Applicants 
## ----------------------------------------------------------------
## Box * White                             -0.0302**               
##                                          (0.0153)               
##                                                                 
## White                                   0.0315***               
##                                          (0.0120)               
##                                                                 
## Box                                       0.0150                
##                                          (0.0245)               
##                                                                 
## Constant                                 0.0847**               
##                                          (0.0387)               
##                                                                 
## Controls - GED                             Yes                  
## Controls - Employment Gap                  Yes                  
## Center FE                                  Yes                  
## Observations                              7,245                 
## R2                                        0.0341                
## Adjusted R2                               0.0222                
## Residual Std. Error                 0.3087 (df = 7156)          
## F Statistic                     2.8693*** (df = 88; 7156)       
## ----------------------------------------------------------------
## Notes:                    ***Significant at the 1 percent level.
##                           **Significant at the 5 percent level. 
##                           *Significant at the 10 percent level.</code></pre>
<p><br></p>
</div>
<div id="section-b-3" class="section level4">
<h4><strong>b)</strong></h4>
<p>What kind of standard errors should you use, and why?</p>
<p><br></p>
<p><strong>Answer</strong> <br> As noted by Agan &amp; Starr (2018), the clustered standard errors on the chain, which all tables above report as “standard errors,” should be used. This is because the entire chains might be sensitive to the “serially correlated shocks,” and because chains have the smaller units, stores, the distribution of which might not be independently and identically distributed, resulting in the correlation of error terms. Clustered errors on the center might give you low p-value more easily since the center is way bigger unit than the chain.</p>
<pre class="r"><code>n_distinct(data$chain_id)</code></pre>
<pre><code>## [1] 293</code></pre>
<pre class="r"><code>n_distinct(data$center)</code></pre>
<pre><code>## [1] 84</code></pre>
<p><br></p>
</div>
<div id="section-c-2" class="section level4">
<h4><strong>c)</strong></h4>
<p>Is the coefficient on “crimbox” statistically significant? What about “white” and the interaction of “crimbox” and “white”? Interpret these findings.</p>
<p><br></p>
<p><strong>Answer</strong> <br> The coefficient on “crimbox” is not statistically significant, but the coefficients on both “white” and the interaction of “crimbox” and “white” are statistically significant. While the difference in the callback rate was not statistically significant between non-white applicants to Box stores and those to non-Box stores, both coefficients regarding the race segregation are found to be statically significant.</p>
<p><span class="math inline">\(\beta_2\)</span> indicates that white applicants to non-Box stores are 3.15 percent points more likely to get the callback than non-white applicants to non_Box stores. <span class="math inline">\(\beta_3\)</span> indicates that the gap in callback rates between white and non-white applicants is 3.02 percent points smaller when they apply to Box stores than non-Box stores.</p>
<p><br></p>
</div>
<div id="section-d" class="section level4">
<h4><strong>d)</strong></h4>
<p>Now estimate the model from question 3 on just “Box” applications in both periods. Interpret the coefficients. (remover == 1)</p>
<p><br></p>
<p><strong>Answer</strong> <br> The callback rate (averaged) for black applicants in the pre-BTB period, controlled for other covariates, or simply <span class="math inline">\(\alpha\)</span>, is 0.1298. <span class="math inline">\(\beta_1\)</span>, the average difference in the callback rate between the applicants in the pre-BTB and post-BTB periods regardless of their races, is -0.0017. <span class="math inline">\(\beta_2\)</span>, the average difference in the callback rate between the White applicants and the Black applicants, regardless of the period, is 0.0401. <span class="math inline">\(\beta_3\)</span> is -0.0327. Except for <span class="math inline">\(\beta_1\)</span>, the other coefficients are found to be statistically significant.</p>
<p><span class="math inline">\(\beta_2\)</span> indicates that white applicants to non-Box stores are 4 percent points more likely to get the callback than non-white applicants in the post-BTB period. <span class="math inline">\(\beta_3\)</span> indicates that the gap in callback rates between white and non-white applicants is 3.27 percent points smaller when they apply in the pre-BTB period than in the post-BTB period.</p>
<p>As discussed in Q3 c), since we limit the data to the BTB complier cases, the Box variable in this all-period regression indicates whether being in the pre-BTB period or not. Then, the fact that <span class="math inline">\(\beta_1\)</span> is not statistically significant shows that there was no difference in non-white applicants’ callback rates between the pre-BTB period and the post-BTB period.</p>
<pre class="r"><code>pre_post_callback &lt;- lm(response ~ box_white + white + crimbox + ged + empgap + factor(center), data = compliers)

# Cluster standard errors
pre_post_callback$clse &lt;- cluster.vcov(pre_post_callback, compliers$chain_id)
pre_post_callback_test &lt;- coeftest(pre_post_callback, pre_post_callback$clse)

# Show Results from Regression
stargazer(
  pre_post_callback,
  type = &quot;text&quot;,
  out = &quot;.txt&quot;,
  style = &quot;aer&quot;,
  digits = 4,
  title = &quot;Effects of Applicant Characteristics on Callback Rates&quot;,
  dep.var.labels = &quot;Callback to Box / non-Box Applicants&quot;,
  covariate.labels = c(&quot;Pre * White&quot;, 
                       &quot;White&quot;,
                       &quot;Pre&quot;),
  omit = c(&quot;ged&quot;, &quot;empgap&quot;, &quot;center&quot;),
  omit.labels = c(&quot;Controls - GED&quot;, &quot;Controls - Employment Gap&quot;, &quot;Center FE&quot;),
  se = list(pre_post_callback_test[, 2])
)</code></pre>
<pre><code>## 
## Effects of Applicant Characteristics on Callback Rates
## ================================================================
##                            Callback to Box / non-Box Applicants 
## ----------------------------------------------------------------
## Pre * White                             -0.0327**               
##                                          (0.0138)               
##                                                                 
## White                                   0.0401***               
##                                          (0.0117)               
##                                                                 
## Pre                                      -0.0017                
##                                          (0.0133)               
##                                                                 
## Constant                                0.1298***               
##                                          (0.0464)               
##                                                                 
## Controls - GED                             Yes                  
## Controls - Employment Gap                  Yes                  
## Center FE                                  Yes                  
## Observations                              4,794                 
## R2                                        0.0437                
## Adjusted R2                               0.0258                
## Residual Std. Error                 0.3205 (df = 4705)          
## F Statistic                     2.4427*** (df = 88; 4705)       
## ----------------------------------------------------------------
## Notes:                    ***Significant at the 1 percent level.
##                           **Significant at the 5 percent level. 
##                           *Significant at the 10 percent level.</code></pre>
<p><br><br></p>
</div>
</div>
<div id="section-q5" class="section level3">
<h3><strong>Q5</strong></h3>
<p>Based on the above analysis, what are your conclusions about the effects of BTB?</p>
<p><br></p>
<p><strong>Answer</strong> <br> The cross-sectional analysis shown in Q4 a) shows that the difference in callback rates bewteen white and non-white applicants was bigger when they applied to non-Box employers than when they applied to Box employers. However, we are not sure whether employers being Box stores or non-Box ones are exogenous, so the difference is caused by the Ban-the-Box policy.</p>
<p>Then, the temporal analysis shown in Q4 d) suggests that while the Ban-the-Box policy do not affect the callback rates of non-white applicants, employers complying with the Ban-the-Box policy discriminate more based on race. Because we limit the data into complier cases, it is reasonable to assume that there was a parallel trend of difference in callback rates between white and non-white applicants in the post-BTB period if the Ban-the-Box policy had not been executed.</p>
<p>To see the effects of BTB more specifically, it might be necessary to do triple difference in order to implement both cross-sectional and temporal analyses at the same time as the authors did.</p>
<p><br><br> Name: Yoon Hong Park</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
